# Generated by Django 3.0.3 on 2020-02-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bhiwandi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_joinee', models.CharField(max_length=60)),
                ('current_ou', models.CharField(max_length=60)),
                ('current_ou_removed', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Lowerparel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_joinee', models.CharField(max_length=60)),
                ('current_ou', models.CharField(max_length=60)),
                ('current_ou_removed', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
