# Generated by Django 3.0.3 on 2020-02-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200217_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhiwandi',
            name='mouse_assigned',
            field=models.CharField(choices=[('DESKTOP', 'DESKTOP'), ('LAPTOP', 'LAPTOP')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='lowerparel',
            name='mouse_assigned',
            field=models.CharField(choices=[('DESKTOP', 'DESKTOP'), ('LAPTOP', 'LAPTOP')], max_length=60, null=True),
        ),
    ]
