# Generated by Django 3.0.3 on 2020-02-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20200217_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhiwandi',
            name='designation',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='lowerparel',
            name='designation',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='bhiwandi',
            name='mouse_assigned',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lowerparel',
            name='mouse_assigned',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=60, null=True),
        ),
    ]
