# Generated by Django 3.0.3 on 2020-02-19 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhiwandi',
            name='date_of_joinee',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lowerparel',
            name='date_of_joinee',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
