# Generated by Django 3.0.3 on 2020-02-19 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20200219_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='date_of_joinee',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
